wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1656395863
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.6.9
      5: 0.12.19
      8:
      - 5
baseline_path:
  desc: null
  value: AD_Baseline
batch_size:
  desc: null
  value: 32
bim_start:
  desc: null
  value: 100
cr_start:
  desc: null
  value: 100
db_path:
  desc: null
  value: database
epochs:
  desc: null
  value: 100
gpu:
  desc: null
  value: '0'
lam_sd:
  desc: null
  value: 0.7
lam_td:
  desc: null
  value: 0.3
save_path:
  desc: null
  value: Logs/save_test
source:
  desc: null
  value: amazon
sp_start:
  desc: null
  value: 100
target:
  desc: null
  value: dslr
th:
  desc: null
  value: 2.0
workers:
  desc: null
  value: 4
